=== UO300627/SEW/xml/circuito.xsd
<?xml version="1.0" encoding="UFT-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema"
	targetNamespace="http://www.uniovi.es"
	xmlns="http://www.uniovi.es"
	elementFormDefault="qualified">	<xs:element name="circuito">
		<xs:complexType>
			<xs:sequence>
				<xs:element ref="nombre" />
				<xs:element ref="longitud" />
				<xs:element ref="anchuraMedia" />
				<xs:element ref="fecha" />
				<xs:element ref="hora" />
				<xs:element ref="numeroVueltas" />
				<xs:element ref="localidadMasProxima" />
				<xs:element ref="pais" />
				<xs:element ref="nombrePatrocinador" />
				<xs:element ref="referencias" />
				<xs:element ref="fotos" />
				<xs:element ref="videos" />
				<xs:element ref="puntoOrigen" />
				<xs:element ref="tramos" />
				<xs:element ref="vencedor" />
				<xs:element ref="clasificacionGeneral" />
			</xs:sequence>
		</xs:complexType>
	</xs:element>
	<xs:element name="nombre" type="xs:string" />
	<xs:element name="longitud">
		<xs:complexType>
			<xs:simpleContent>
				<xs:extension base="tipoLongitud">
					<xs:attribute name="unidad" type="xs:string" use="required" />
				</xs:extension>
			</xs:simpleContent>
		</xs:complexType>
	</xs:element>

	<xs:simpleType name="tipoLongitud">
		<xs:restriction base="xs:nonNegativeInteger">
			<xs:maxInclusive value="25000" />
		</xs:restriction>
	</xs:simpleType>

	<xs:element name="anchuraMedia">
		<xs:complexType>
			<xs:simpleContent>
				<xs:extension base="tipoAnchuraMedia">
					<xs:attribute name="unidad" type="xs:string" use="required" />
				</xs:extension>
			</xs:simpleContent>
		</xs:complexType>
	</xs:element>

	<xs:simpleType name="tipoAnchuraMedia">
		<xs:restriction base="xs:nonNegativeInteger">
			<xs:maxInclusive value="200" />
		</xs:restriction>
	</xs:simpleType>

	<xs:element name="fecha" type="xs:date" />
	<xs:element name="hora" type="xs:time" />
	<xs:element name="numeroVueltas" type="xs:nonNegativeInteger" />
	<xs:element name="localidadMasProxima" type="xs:string" />
	<xs:element name="pais" type="xs:string" />
	<xs:element name="nombrePatrocinador" type="xs:string" />
	<xs:element name="referencias">
		<xs:complexType>
			<xs:sequence>
				<xs:element minOccurs="3" maxOccurs="unbounded" ref="referencia" />
			</xs:sequence>
		</xs:complexType>
	</xs:element>
	<xs:element name="referencia">
		<xs:complexType>
			<xs:simpleContent>
				<xs:extension base="xs:string">
					<xs:attribute name="texto" type="xs:string" use="required" />
				</xs:extension>
			</xs:simpleContent>
		</xs:complexType>
	</xs:element>
	<xs:element name="fotos">
		<xs:complexType>
			<xs:sequence>
				<xs:element minOccurs="3" maxOccurs="unbounded" ref="foto" />
			</xs:sequence>
		</xs:complexType>
	</xs:element>
	<xs:element name="foto">
		<xs:complexType>
			<xs:simpleContent>
				<xs:extension base="xs:string">
					<xs:attribute name="descripcion" type="xs:string" />
				</xs:extension>
			</xs:simpleContent>
		</xs:complexType>
	</xs:element>
	<xs:element name="videos">
		<xs:complexType>
			<xs:sequence>
				<xs:element minOccurs="1" maxOccurs="3" ref="video" />
			</xs:sequence>
		</xs:complexType>
	</xs:element>
	<xs:element name="video">
		<xs:complexType>
			<xs:simpleContent>
				<xs:extension base="xs:string">
					<xs:attribute name="descripcion" type="xs:string" />
				</xs:extension>
			</xs:simpleContent>
		</xs:complexType>
	</xs:element>
	<xs:element name="puntoOrigen">
		<xs:complexType>
			<xs:sequence>
				<xs:element ref="coordenada" />
			</xs:sequence>
		</xs:complexType>
	</xs:element>
	<xs:element name="coordenada">
		<xs:complexType>
			<xs:sequence>
				<xs:element ref="longitudPunto" />
				<xs:element ref="latitudPunto" />
				<xs:element ref="altitudPunto" />
			</xs:sequence>
		</xs:complexType>
	</xs:element>
	<xs:element name="longitudPunto">
		<xs:complexType>
			<xs:simpleContent>
				<xs:extension base="tipoLongitudPunto">
					<xs:attribute name="unidad" type="xs:string" use="required" />
				</xs:extension>
			</xs:simpleContent>
		</xs:complexType>
	</xs:element>

	<xs:simpleType name="tipoLongitudPunto">
		<xs:restriction base="xs:decimal">
			<xs:minInclusive value="-180" />
			<xs:maxInclusive value="180" />
		</xs:restriction>
	</xs:simpleType>

	<xs:element name="latitudPunto">
		<xs:complexType>
			<xs:simpleContent>
				<xs:extension base="tipoLatitudPunto">
					<xs:attribute name="unidad" type="xs:string" use="required" />
				</xs:extension>
			</xs:simpleContent>
		</xs:complexType>
	</xs:element>

	<xs:simpleType name="tipoLatitudPunto">
		<xs:restriction base="xs:decimal">
			<xs:minInclusive value="-90" />
			<xs:maxInclusive value="90" />
		</xs:restriction>
	</xs:simpleType>

	<xs:element name="altitudPunto">
		<xs:complexType>
			<xs:simpleContent>
				<xs:extension base="tipoAltitudPunto">
					<xs:attribute name="unidad" type="xs:string" use="required" />
				</xs:extension>
			</xs:simpleContent>
		</xs:complexType>
	</xs:element>

	<xs:simpleType name="tipoAltitudPunto">
		<xs:restriction base="xs:nonNegativeInteger">
			<xs:maxInclusive value="5000" />
		</xs:restriction>
	</xs:simpleType>
	<xs:element name="tramos">
		<xs:complexType>
			<xs:sequence>
				<xs:element minOccurs="1" maxOccurs="unbounded" ref="tramo" />
			</xs:sequence>
		</xs:complexType>
	</xs:element>
	<xs:element name="tramo">
		<xs:complexType>
			<xs:sequence>
				<xs:element ref="distancia" />
				<xs:element ref="coordenada" />
				<xs:element ref="sector" />
			</xs:sequence>
		</xs:complexType>
	</xs:element>
	<xs:element name="distancia">
		<xs:complexType>
			<xs:simpleContent>
				<xs:extension base="xs:decimal">
					<xs:attribute name="unidad" type="xs:string" use="required" />
				</xs:extension>
			</xs:simpleContent>
		</xs:complexType>
	</xs:element>
	<xs:element name="sector" type="xs:string" /> 
	<xs:element name="vencedor">
		<xs:complexType>
			<xs:simpleContent>
				<xs:extension base="xs:string">
					<xs:attribute name="tiempoEmpleado" type="xs:duration" use="required" />
				</xs:extension>
			</xs:simpleContent>
		</xs:complexType>
	</xs:element>
	<xs:element name="clasificacionGeneral">
		<xs:complexType>
			<xs:sequence>
				<xs:element ref="primero" />
				<xs:element ref="segundo" />
				<xs:element ref="tercero" />
			</xs:sequence>
		</xs:complexType>
	</xs:element>
	<xs:element name="primero" type="xs:string" />
	<xs:element name="segundo" type="xs:string" />
	<xs:element name="tercero" type="xs:string" />
</xs:schema>

=== UO300627/SEW/xml/circuitoEsquema.xml
<?xml version="1.0" encoding="UTF-8"?>
<circuito xmlns="http://www.uniovi.es"
	xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
	xsi:schemaLocation="http://www.uniovi.es circuito.xsd">

    <nombre>Petronas Sepang International Circuit</nombre>
    <longitud unidad="metros">5543</longitud>
    <anchuraMedia unidad="metros">19</anchuraMedia>
    <fecha>2025-10-26</fecha>
    <hora>12:40:00</hora>
    <numeroVueltas>20</numeroVueltas>
    <localidadMasProxima>Kuala Lumpur</localidadMasProxima>
    <pais>Malasia</pais>
    <nombrePatrocinador>Petronas</nombrePatrocinador>
    <referencias>
        <referencia texto = "Página oficial del circuito" >https://www.sepangcircuit.com/</referencia>
        <referencia texto = "Información sobre el Gran Premio en la página oficial de MotoGP">https://www.motogp.com/es/calendar/2025/event/malaysia/c2cd8f49-5643-440f-84fc-4c37b3ef3f87?tab=overview</referencia>
        <referencia texto = "Información sobre el circuito">https://ssrexperience.com/es/servicios/sepang/</referencia>
    </referencias>
    <fotos>
        <foto descripcion = "Trazado del circuito">../multimedia/trazadoCircuito.jpg</foto>
        <foto descripcion = "Panorámica del circuito">../multimedia/panoramicaCircuito.jpg</foto>
        <foto descripcion = "Recta de salida del circuito">../multimedia/rectaSalida.jpg</foto>
    </fotos>
    <videos>
        <video descripcion = "Piloto corriendo en el circuito">../multimedia/videoRecorridoCircuito.mp4</video>
    </videos>
    <puntoOrigen>
        <coordenada>
            <longitudPunto unidad="decimal">101.738375</longitudPunto>
            <latitudPunto unidad="decimal">2.760762</latitudPunto>
            <altitudPunto unidad="metros">36</altitudPunto>
        </coordenada>         
    </puntoOrigen>

    <tramos>
        <tramo>
            <distancia unidad="metros">620.7</distancia>
            <coordenada>
                <longitudPunto unidad="decimal">101.732807</longitudPunto>
                <latitudPunto unidad="decimal">2.760338</latitudPunto>
                <altitudPunto unidad="metros">38</altitudPunto>
            </coordenada>           
            <sector>1</sector>
        </tramo>

        <tramo>
            <distancia unidad="metros">46.63</distancia>
            <coordenada>
                <longitudPunto unidad="decimal">101.732609</longitudPunto>
                <latitudPunto unidad="decimal">2.760710</latitudPunto>
                <altitudPunto unidad="metros">37</altitudPunto>
            </coordenada>           
            <sector>1</sector>
        </tramo>

        <tramo>
            <distancia unidad="metros">40.59</distancia>
            <coordenada>
                <longitudPunto unidad="decimal">101.732866</longitudPunto>
                <latitudPunto unidad="decimal">2.760966</latitudPunto>
                <altitudPunto unidad="metros">37</altitudPunto>
            </coordenada>           
            <sector>1</sector>
        </tramo>

        <tramo>
            <distancia unidad="metros">65.53</distancia>
            <coordenada>
                <longitudPunto unidad="decimal">101.733444</longitudPunto>
                <latitudPunto unidad="decimal">2.760841</latitudPunto>
                <altitudPunto unidad="metros">36</altitudPunto>
            </coordenada>
            <sector>1</sector>
        </tramo>

        <tramo>
            <distancia unidad="metros">39.74</distancia>
            <coordenada>
                <longitudPunto unidad="decimal">101.733570</longitudPunto>
                <latitudPunto unidad="decimal">2.761177</latitudPunto>
                <altitudPunto unidad="metros">34</altitudPunto>
            </coordenada>
            <sector>1</sector>
        </tramo>

        <tramo>
            <distancia unidad="metros">100.81</distancia>
            <coordenada>
                <longitudPunto unidad="decimal">101.733091</longitudPunto>
                <latitudPunto unidad="decimal">2.761952</latitudPunto>
                <altitudPunto unidad="metros">29</altitudPunto>
            </coordenada>
            <sector>1</sector>
        </tramo>

        <tramo>
            <distancia unidad="metros">121.88</distancia>
            <coordenada>
                <longitudPunto unidad="decimal">101.733196</longitudPunto>
                <latitudPunto unidad="decimal">2.763050</latitudPunto>
                <altitudPunto unidad="metros">24</altitudPunto>                  
            </coordenada>
            <sector>1</sector>
        </tramo>

        <tramo>
            <distancia unidad="metros">98.89</distancia>
            <coordenada>
                <longitudPunto unidad="decimal">101.733738</longitudPunto>
                <latitudPunto unidad="decimal">2.763754</latitudPunto>
                <altitudPunto unidad="metros">23</altitudPunto>
            </coordenada>            
            <sector>1</sector>
        </tramo>
            
        <tramo>
            <distancia unidad="metros">32.53</distancia>
            <coordenada>
                <longitudPunto unidad="decimal">101.734008</longitudPunto>
                <latitudPunto unidad="decimal">2.763870</latitudPunto>
                <altitudPunto unidad="metros">23</altitudPunto>
            </coordenada>            
            <sector>1</sector>
        </tramo>

        <tramo>
            <distancia unidad="metros">184.56</distancia>
            <coordenada>
                <longitudPunto unidad="decimal">101.735582</longitudPunto>
                <latitudPunto unidad="decimal">2.764404</latitudPunto>
                <altitudPunto unidad="metros">27</altitudPunto>
            </coordenada>
            <sector>2</sector>
        </tramo>

        <tramo>
            <distancia unidad="metros">212.71</distancia>
            <coordenada>
                <longitudPunto unidad="decimal">101.737341</longitudPunto>
                <latitudPunto unidad="decimal">2.765158</latitudPunto>
                <altitudPunto unidad="metros">36</altitudPunto>
            </coordenada>
            <sector>2</sector>
        </tramo>

        <tramo>
            <distancia unidad="metros">25.02</distancia>
            <coordenada>
                <longitudPunto unidad="decimal">101.737566</longitudPunto>
                <latitudPunto unidad="decimal">2.765152</latitudPunto>
                <altitudPunto unidad="metros">37</altitudPunto>
            </coordenada>
            <sector>2</sector>
        </tramo>

        <tramo>
            <distancia unidad="metros">25.16</distancia>
            <coordenada>
                <longitudPunto unidad="decimal">101.737657</longitudPunto>
                <latitudPunto unidad="decimal">2.764944</latitudPunto>
                <altitudPunto unidad="metros">38</altitudPunto>
            </coordenada>
            <sector>2</sector>
        </tramo>

        <tramo>
            <distancia unidad="metros">250.7</distancia>
            <coordenada>
                <longitudPunto unidad="decimal">101.738150</longitudPunto>
                <latitudPunto unidad="decimal">2.762731</latitudPunto>
                <altitudPunto unidad="metros">39</altitudPunto>
            </coordenada>
            <sector>2</sector>
        </tramo>

        <tramo>
            <distancia unidad="metros">73.28</distancia>
            <coordenada>
                <longitudPunto unidad="decimal">101.738644</longitudPunto>
                <latitudPunto unidad="decimal">2.762292</latitudPunto>
                <altitudPunto unidad="metros">37</altitudPunto>
            </coordenada>
            <sector>2</sector>
        </tramo>

        <tramo>
            <distancia unidad="metros">67.09</distancia>
            <coordenada>
                <longitudPunto unidad="decimal">101.739242</longitudPunto>
                <latitudPunto unidad="decimal">2.762226</latitudPunto>
                <altitudPunto unidad="metros">36</altitudPunto>
            </coordenada>
            <sector>2</sector>
        </tramo>

        <tramo>
            <distancia unidad="metros">65.11</distancia>
            <coordenada>
                <longitudPunto unidad="decimal">101.739771</longitudPunto>
                <latitudPunto unidad="decimal">2.762478</latitudPunto>
                <altitudPunto unidad="metros">37</altitudPunto>
            </coordenada>
            <sector>2</sector>
        </tramo>

        <tramo>
            <distancia unidad="metros">53.14</distancia>
            <coordenada>
                <longitudPunto unidad="decimal">101.740102</longitudPunto>
                <latitudPunto unidad="decimal">2.762824</latitudPunto>
                <altitudPunto unidad="metros">38</altitudPunto>
            </coordenada>
            <sector>2</sector>
        </tramo>

        <tramo>
            <distancia unidad="metros">48.71</distancia>
            <coordenada>
                <longitudPunto unidad="decimal">101.740508</longitudPunto>
                <latitudPunto unidad="decimal">2.762989</latitudPunto>
                <altitudPunto unidad="metros">39</altitudPunto>
            </coordenada>
            <sector>2</sector>
        </tramo>

        <tramo>
            <distancia unidad="metros">73.8</distancia>
            <coordenada>
                <longitudPunto unidad="decimal">101.741154</longitudPunto>
                <latitudPunto unidad="decimal">2.762837</latitudPunto>
                <altitudPunto unidad="metros">39</altitudPunto>
            </coordenada>
            <sector>2</sector>
        </tramo>

        <tramo>
            <distancia unidad="metros">215.04</distancia>
            <coordenada>
                <longitudPunto unidad="decimal">101.742443</longitudPunto>
